{% set version = '0.5.0' %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-cbctools
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/cbcTools_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/cbcTools/cbcTools_{{ version }}.tar.gz
  sha256: 5c1a07e1e4b939411e223934ea884339f00983be54413dbcf043d86301d20a1e

build:
  merge_build_host: True  # [win]
  number: 0
  noarch: generic
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ posix }}zip               # [win]
    - cross-r-base {{ r_base }}    # [build_platform != target_platform]
  host:
    - r-base
    - r-algdesign
    - r-doe.base
    - r-mass
    - r-fastdummies
    - r-ggplot2
    - r-idefix
    - r-logitr >=1.0.1
    - r-randtoolbox
    - r-rlang
  run:
    - r-base
    - r-algdesign
    - r-doe.base
    - r-mass
    - r-fastdummies
    - r-ggplot2
    - r-idefix
    - r-logitr >=1.0.1
    - r-randtoolbox
    - r-rlang

test:
  commands:
    - $R -e "library('cbcTools')"           # [not win]
    - "\"%R%\" -e \"library('cbcTools')\""  # [win]

about:
  home: https://github.com/jhelvy/cbcTools
  license: MIT
  summary: "Design and evaluate choice-based conjoint survey experiments. Generate a variety
    of survey designs, including random designs, full factorial designs, orthogonal
    designs, D-optimal designs, and Bayesian D-efficient designs as well as designs
    with \"no choice\" options and \"labeled\" (also known as \"alternative specific\")
    designs. Conveniently inspect the design balance and overlap, and simulate choice
    data for a survey design either randomly or according to a multinomial or mixed
    logit utility model defined by user-provided prior parameters. Conduct a power analysis
    for a given survey design by estimating the same model on different subsets of the
    data to simulate different sample sizes. Full factorial and orthogonal designs are
    obtained using the 'DoE.base' package (Gr\xF6mping, 2018) <doi:10.18637/jss.v085.i05>.
    D-optimal designs are obtained using the 'AlgDesign' package (Wheeler, 2022) <https://CRAN.R-project.org/package=AlgDesign>.
    Bayesian D-efficient designs are obtained using the 'idefix' package (Traets et
    al, 2020) <doi:10.18637/jss.v096.i03>. Choice simulation and model estimation in
    power analyses are handled using the 'logitr' package (Helveston, 2023) <doi:10.18637/jss.v105.i10>."
  license_family: MIT
  license_file:
    - '{{ environ["PREFIX"] }}/lib/R/share/licenses/MIT'
    - LICENSE

extra:
  recipe-maintainers:
    - conda-forge/r
    - tobiasraabe

# Package: cbcTools
# Title: Choice-Based Conjoint Experiment Design Generation and Power Evaluation in R
# Version: 0.5.0
# Maintainer: John Helveston <john.helveston@gmail.com>
# Authors@R: c( person(given   = "John", family  = "Helveston", role    = c("cre", "aut", "cph"), email   = "john.helveston@gmail.com", comment = c(ORCID = "0000-0002-2657-9191")))
# Description: Design and evaluate choice-based conjoint survey experiments. Generate a variety of survey designs, including random designs, full factorial designs, orthogonal designs, D-optimal designs, and Bayesian D-efficient designs as well as designs with "no choice" options and "labeled" (also known as "alternative specific") designs. Conveniently inspect the design balance and overlap, and simulate choice data for a survey design either randomly or according to a multinomial or mixed logit utility model defined by user-provided prior parameters. Conduct a power analysis for a given survey design by estimating the same model on different subsets of the data to simulate different sample sizes. Full factorial and orthogonal designs are obtained using the 'DoE.base' package (Gromping, 2018) <doi:10.18637/jss.v085.i05>. D-optimal designs are obtained using the 'AlgDesign' package (Wheeler, 2022) <https://CRAN.R-project.org/package=AlgDesign>. Bayesian D-efficient designs are obtained using the 'idefix' package (Traets et al, 2020) <doi:10.18637/jss.v096.i03>. Choice simulation and model estimation in power analyses are handled using the 'logitr' package (Helveston, 2023) <doi:10.18637/jss.v105.i10>.
# License: MIT + file LICENSE
# Encoding: UTF-8
# RoxygenNote: 7.2.3
# VignetteBuilder: knitr
# Depends: R (>= 3.5.0)
# Suggests: here, knitr, testthat, tibble
# Imports: AlgDesign, DoE.base, fastDummies, ggplot2, idefix, logitr (>= 1.0.1), MASS, parallel, randtoolbox, rlang, stats, utils
# URL: https://github.com/jhelvy/cbcTools
# BugReports: https://github.com/jhelvy/cbcTools/issues
# NeedsCompilation: no
# Packaged: 2023-07-11 10:06:34 UTC; jhelvy
# Author: John Helveston [cre, aut, cph] (<https://orcid.org/0000-0002-2657-9191>)
# Repository: CRAN
# Date/Publication: 2023-07-12 22:30:15 UTC
